GET http://localhost:5298/games

###
POST http://localhost:5298/games
Content-Type: application/json

{
  "Name": "RDR 2",
  "Genreid": 1,
  "Price": 59.99,
  "ReleaseDate": "2024-12-01"
}

### update
PUT http://localhost:5298/games/5
Content-Type: application/json

{
  "Name": "Super Mario Odyssey",
  "GenreID": 2,
  "Price": 59.99,
  "ReleaseDate": "2020-12-01"
}


### Delete

DELETE http://localhost:5298/games/1
